; Максимальный размер одного загружаемого файла
upload_max_filesize = 200M

; Максимальный размер ВСЕХ данных POST-запроса (должен быть >= upload_max_filesize)
post_max_size = 200M

; Максимальное время выполнения скрипта (в секундах)
max_execution_time = 300

; Максимальное время на разбор входных данных (парсинг запроса, включая загрузку файла)
max_input_time = 300

; Лимит памяти для PHP-скрипта
memory_limit = 256M

; Максимальное количество файлов, загружаемых за один раз
max_file_uploads = 20
